### ISSUE TITLE
Stale python-bitcoinlib==0.5.1 requirement if master branch was used before

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/federatednode#300]
When I rebuild & reparse to get around https://github.com/CounterpartyXCP/counterparty-lib/issues/950, I hit https://github.com/CounterpartyXCP/counterparty-cli/issues/111.

This affects both counterparty* and counterblock* containers, so the workaround from https://github.com/CounterpartyXCP/counterparty-lib/issues/950#issuecomment-294302718 doesn't appear to work (note that `Requirement.parse('python-bitcoinlib==0.5.1'), {'counterparty-lib'})` appears in the error) **if** you initially installed from `master`. 
For reference, a temporary fix that also works in FedNode if you don't have stale `master` bits was made [here](https://github.com/CounterpartyXCP/counterparty-lib/commit/5317d7f5c6508be22af236d72838c0d00998685a).

```
$ fednode reparse counterparty-testnet
TESTNET USE DETECTED -- GETTING python-bitcoinlib 0.7.1-SNAPSHOT
Collecting python-bitcoinlib-0.7.1-SNAPSHOT from git+https://github.com/VidaID/python-bitcoinlib.git@5cd34672d7085ca4d55693a1008101c02ceeb7e9#egg=python-bitcoinlib-0.7.1-SNAPSHOT
  Cloning https://github.com/VidaID/python-bitcoinlib.git (to 5cd34672d7085ca4d55693a1008101c02ceeb7e9) to /tmp/pip-build-8d41rj2n/python-bitcoinlib-0.7.1-SNAPSHOT
  Could not find a tag or branch '5cd34672d7085ca4d55693a1008101c02ceeb7e9', assuming commit.
  Running setup.py (path:/tmp/pip-build-8d41rj2n/python-bitcoinlib-0.7.1-SNAPSHOT/setup.py) egg_info for package python-bitcoinlib-0.7.1-SNAPSHOT produced metadata for project name python-bitcoinlib. Fix your #egg=python-bitcoinlib-0.7.1-SNAPSHOT fragments.
Installing collected packages: python-bitcoinlib
  Running setup.py install for python-bitcoinlib ... done
Successfully installed python-bitcoinlib-0.7.1-SNAPSHOT
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-bitcoinlib 0.7.1-SNAPSHOT (/usr/local/lib/python3.5/dist-packages), Requirement.parse('python-bitcoinlib==0.5.1'), {'counterparty-lib'})
```

A workaround start with `develop` or, if you have installed from `master` before then move federatednode/src, clone fednode repo again and build from `develop`.

**Comment by unsystemizer** [comment]
I'll close this since it's not really a bug, it's enough to have it recorded in issues.
