### ISSUE TITLE
counterparty-client in testnet container requires --testnet

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/federatednode#303]
This is with v2.2.3 (`fednode install counterblock master`).

`testnet=1` (in client.testnet.conf) should be enough, but it isn't. Even if I add `counterparty-rpc-port=14000` and restart, the client still insists on connecting to mainnet (4000).

It is because it actually behaves like a normal non-containerized client: it reads client.conf (for mainnet containers).
If I inject `testnet=1` to `config/counterparty/client.conf`, I don't need to pass `--testnet` in counterparty-testnet. The same problem maybe applies to some other testnet containers.

```
user@ubuntu:~/federatednode$ cat config/counterparty/client.testnet.conf
[Default]
testnet=1
counterparty-rpc-password=rpc
wallet-connect=bitcoin-testnet
wallet-user=rpc
wallet-password=rpc

user@ubuntu:~/federatednode$ fednode shell counterparty-testnet

root@ubuntu-cp-t:/# counterparty-client getinfo
[2017-05-02 05:56:38][INFO] Running v1.1.3 of counterparty-client.
Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-client", line 9, in <module>
    load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-client')()
  File "/counterparty-cli/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/counterparty-cli/counterpartycli/client.py", line 247, in main
    view = console.get_view(args.action, args)
  File "/counterparty-cli/counterpartycli/console.py", line 16, in get_view
    return util.api('get_running_info')
  File "/counterparty-cli/counterpartycli/util.py", line 92, in api
    return rpc(config.COUNTERPARTY_RPC, method, params=params, ssl_verify=config.COUNTERPARTY_RPC_SSL_VERIFY)
  File "/counterparty-cli/counterpartycli/util.py", line 80, in rpc
    raise RPCError('Cannot communicate with {}.'.format(url))
counterpartycli.util.RPCError: Cannot communicate with http://rpc:rpc@localhost:4000/rpc/.

root@ubuntu-cp-t:/# counterparty-client --testnet getinfo
[2017-05-02 05:56:47][INFO] Running v1.1.3 of counterparty-client.
{
    "bitcoin_block_count": 1121348,
    "db_caught_up": true,
    "last_block": {
        "block_hash": "0000000000000808bce9826d2f67b054b181893d909d12271d82b98bb4c40f07",
        "block_index": 1121348,
        "block_time": 1493704477,
        "difficulty": 1397872.034113577,
        "ledger_hash": "bf4f2e6426c89cf22b659634128c51b40ad084550dbbe5203508edf7626bb1d1",
        "messages_hash": "423014c101103e10210fa9ba8a46f3a4bfaefc84d842eb3b05e4e56e7d0edabe",
        "previous_block_hash": "00000000000005c6db49d727d6fcd1faa9b53baadbd190c11761e34fb3760f76",
        "txlist_hash": "eac0ee3e1859d7cd954ae4750f2c84059249bfbb56ea713f3890ae722a25d5b4"
    },
    "last_message_index": 38693,
    "running_testcoin": false,
    "running_testnet": true,
    "version_major": 9,
    "version_minor": 55,
    "version_revision": 2
}

```

**Comment by longhoangwkm** [comment]
i also got this errror. But even i add `--testnet` then it still not work
