### ISSUE TITLE
counterparty.testnet.db corrupt upon installation

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/federatednode#309]
counterparty-testnet can't start upon installation. I stopped it once (because services start automatically upon installation) and next time I tried to start testnet DB was corrupt and 763412480 bytes (don't know why this size) large which is funny because I stopped all services about 1 minute after installation so it couldn't have caught up that much. 

```
counterparty-testnet_1  | [2017-09-09 15:37:35][INFO] Running v1.1.3 of counterparty-server.
counterparty-testnet_1  | [2017-09-09 15:37:35][INFO] Running v9.55.2 of counterparty-lib.
counterparty-testnet_1  | [2017-09-09 15:37:35][INFO] Acquiring lock.
counterparty-testnet_1  | [2017-09-09 15:37:35][INFO] Connecting to database.
counterparty-testnet_1  | [2017-09-09 15:37:35][ERROR] Unhandled Exception
counterparty-testnet_1  | Traceback (most recent call last):
counterparty-testnet_1  |   File "/usr/local/bin/counterparty-server", line 9, in <module>
counterparty-testnet_1  |     load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
counterparty-testnet_1  |   File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
counterparty-testnet_1  |     server.main()
counterparty-testnet_1  |   File "/counterparty-cli/counterpartycli/server.py", line 141, in main
counterparty-testnet_1  |     db = init_with_catch(server.initialise, init_args)
counterparty-testnet_1  |   File "/counterparty-cli/counterpartycli/server.py", line 107, in init_with_catch
counterparty-testnet_1  |     return fn(**init_args)
counterparty-testnet_1  |   File "/counterparty-lib/counterpartylib/server.py", line 79, in initialise
counterparty-testnet_1  |     return initialise_db()
counterparty-testnet_1  |   File "/counterparty-lib/counterpartylib/server.py", line 379, in initialise_db
counterparty-testnet_1  |     db = database.get_connection(read_only=False)
counterparty-testnet_1  |   File "/counterparty-lib/counterpartylib/lib/database.py", line 88, in get_connection
counterparty-testnet_1  |     rows = list(cursor.execute('''PRAGMA foreign_key_check'''))
counterparty-testnet_1  |   File "src/cursor.c", line 990, in APSWCursor_execute.sqlite3_prepare
counterparty-testnet_1  |   File "src/statementcache.c", line 386, in sqlite3_prepare
counterparty-testnet_1  | apsw.CorruptError: CorruptError: database disk image is malformed
federatednode_counterparty-testnet_1 exited with code 0

```
Manual fix:

```
sudo -s
cd /var/lib/docker/volumes/federatednode_counterparty-data/_data
wget https://s3.amazonaws.com/counterparty-bootstrap/counterparty-db-testnet.latest.tar.gz
```

Decompress, verify checksum, start the container again.
Downloaded and decompressed counterparty.testnet.db is 819036160 bytes, so quite a bit larger than the one I had. 

With this I was able to start normally using `fednode start counterparty-testnet`:

```
counterparty-testnet_1  | You are using pip version 8.1.1, however version 9.0.1 is available.
counterparty-testnet_1  | You should consider upgrading via the 'pip install --upgrade pip' command.
counterparty-testnet_1  | [2017-09-09 15:47:02][INFO] Running v1.1.3 of counterparty-server.
counterparty-testnet_1  | [2017-09-09 15:47:02][INFO] Running v9.55.2 of counterparty-lib.
counterparty-testnet_1  | [2017-09-09 15:47:02][INFO] Acquiring lock.
counterparty-testnet_1  | [2017-09-09 15:47:02][INFO] Connecting to database.
counterparty-testnet_1  | [2017-09-09 15:47:11][INFO] Connecting to backend.
counterparty-testnet_1  | [2017-09-09 15:47:11][INFO] Starting API Server.
```

**Comment by jdogresorg** [comment]
At some point in the past a bad bootstrap version was uploaded to production, no one noticed, and the hashes were changed to match the bootstrap version so that everything kept running smoothly.

A couple months ago I did a full parse of testnet **_NOT_** using the bootstrap and counterparty kept dying on the same block 650,000 because the hashes did not match.... after working with @deweller, he too did a parse and saw the failure.

The solution was to :
1.) Do a full parse of testnet from bitcoin (no bootstrap download)
2.) Upload a the uncorrupted/valid version of counterparty-testnet
3.) Fix testnet hashes so that they match the new bootstrap file.

**Comment by unsystemizer** [comment]
This is still a problem with `master` (candidate for 9.55.3). Testnet can't run without a workaround.

**Comment by unsystemizer** [comment]
Reported today by mandelDuck - still a problem.

**Comment by cryptcoin-junkey** [comment]
It may be a separate issue from this.

In a case on calling 'rebuild' on develop mode, DB may be broken by https://github.com/CounterpartyXCP/counterparty-lib/pull/1014.
